-- Image Judge schema for Supabase (Postgres). Safe to run more than once.
--
-- Same tables as the local SQLite file, so the app code is shared. JSON columns are jsonb so the
-- data can be queried and exported for training; the app reads them back as text.
--
-- SECURITY: row-level security is switched on for every table and NO policies are created. That means
-- Supabase's public REST API (the anon / authenticated keys) can read and write nothing. Only a direct
-- database connection (the IMAGE_JUDGE_DATABASE_URL connection string) and the service role can.
-- Keep both of those secret. Do not add permissive policies unless you also add real user login.

CREATE TABLE IF NOT EXISTS evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at DOUBLE PRECISION NOT NULL,
    prompt TEXT NOT NULL,
    images JSONB NOT NULL,          -- {"originals": [names], "a": name, "b": name}
    config JSONB NOT NULL,
    status TEXT NOT NULL,           -- confident | review | unclear | error
    verdict TEXT,                   -- A | B | NULL
    result JSONB NOT NULL,
    knowledge_id BIGINT,
    set_task_id BIGINT,
    created_by TEXT NOT NULL DEFAULT ''      -- who ran it (hosted app)
);

CREATE TABLE IF NOT EXISTS feedback (
    evaluation_id BIGINT PRIMARY KEY REFERENCES evaluations(id) ON DELETE CASCADE,
    created_at DOUBLE PRECISION NOT NULL,
    verdict_correct INTEGER,        -- 1 right, 0 wrong, NULL when there was no verdict
    true_label TEXT NOT NULL,       -- A | B
    reason TEXT NOT NULL DEFAULT '', -- why the correct result is correct (best training signal)
    labelled_by TEXT NOT NULL DEFAULT ''  -- who gave the answer (hosted app)
);

CREATE TABLE IF NOT EXISTS judge_cache (
    key TEXT PRIMARY KEY,
    created_at DOUBLE PRECISION NOT NULL,
    judgment JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS task_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at DOUBLE PRECISION NOT NULL,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS set_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL REFERENCES task_sets(id) ON DELETE CASCADE,
    created_at DOUBLE PRECISION NOT NULL,
    prompt TEXT NOT NULL,
    images JSONB NOT NULL,          -- {"originals": [names], "a": name, "b": name}
    label TEXT,                     -- A | B | NULL (not known yet)
    created_by TEXT NOT NULL DEFAULT '',
    labelled_by TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS set_tasks_set_id_idx ON set_tasks(set_id);

CREATE TABLE IF NOT EXISTS knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at DOUBLE PRECISION NOT NULL,
    parent_id BIGINT,
    guidelines TEXT NOT NULL DEFAULT '',
    lessons JSONB NOT NULL DEFAULT '[]'::jsonb,
    source TEXT NOT NULL DEFAULT '',
    active INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'accepted',    -- accepted | candidate | superseded | rejected
    learned_from JSONB NOT NULL DEFAULT '[]'::jsonb,  -- set-task ids the lessons were learned from
    gate_result JSONB,                          -- how the held-out test went
    author TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS benchmark_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at DOUBLE PRECISION NOT NULL,
    finished_at DOUBLE PRECISION,
    dataset TEXT NOT NULL,
    config JSONB NOT NULL,
    status TEXT NOT NULL,           -- running | done | failed | interrupted
    total INTEGER NOT NULL DEFAULT 0,
    completed INTEGER NOT NULL DEFAULT 0,
    metrics JSONB,
    note TEXT,
    mode TEXT NOT NULL DEFAULT 'benchmark',   -- benchmark | train | test | judge
    set_id BIGINT,
    started_by TEXT NOT NULL DEFAULT '',
    knowledge_id BIGINT,
    learned_knowledge_id BIGINT,
    baseline_of BIGINT
);

CREATE TABLE IF NOT EXISTS benchmark_items (
    run_id BIGINT NOT NULL REFERENCES benchmark_runs(id) ON DELETE CASCADE,
    task_id TEXT NOT NULL,
    label TEXT NOT NULL,
    status TEXT NOT NULL,
    verdict TEXT,
    correct INTEGER,
    result JSONB NOT NULL,
    PRIMARY KEY (run_id, task_id)
);

-- No public access (see the note at the top).
ALTER TABLE evaluations      ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedback         ENABLE ROW LEVEL SECURITY;
ALTER TABLE judge_cache      ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_sets        ENABLE ROW LEVEL SECURITY;
ALTER TABLE set_tasks        ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge        ENABLE ROW LEVEL SECURITY;
ALTER TABLE benchmark_runs   ENABLE ROW LEVEL SECURITY;
ALTER TABLE benchmark_items  ENABLE ROW LEVEL SECURITY;
